services:
  api-dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: taskflow-api-dev
    env_file:
      - .env
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  api-prod:
    profiles: ["prod"]
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskflow-api-prod
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    command: node dist/main
