FROM node:24-slim

WORKDIR /usr/src/app

COPY package*.json ./
COPY apps/api/package.json apps/api/package.json

RUN npm install
RUN npm install -g @nestjs/cli

EXPOSE 3000

CMD ["npm", "run", "start:dev", "-w", "apps/api"]
